CREATE TABLE [dbo].[GC_FIELD_INFO](
	[DATA_TABLE_NAME] [varchar](100) NOT NULL,
	[FIELD_NAME] [varchar](100) NOT NULL,
	[REQUIRED_FILE_DIRECTOR_FLAG] [char](1) NOT NULL,
	[OUTPUT_ORDER] [varchar](100) NULL
) ON [PRIMARY]