CREATE TABLE [dbo].[GC_FORM_INFO](
	[FORM_NAME] [varchar](100) NOT NULL,
	[ABBYY_FORM_NAME] [varchar](100) NOT NULL,
	[DATA_TABLE] [varchar](100) NOT NULL,
	[EXPORT_DIRECTORY] [varchar](100) NOT NULL,
	[EXCEPTIONAL_EXPORT] [varchar](100) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GC_FORM_INFO] ADD  CONSTRAINT [DF_GC_FORM_INFO_EXPORT_EXCEPTION_]  DEFAULT ('N') FOR [EXCEPTIONAL_EXPORT]