CREATE TABLE [dbo].[RC_GAE_INTERMEDIATE](
	[URN] [nvarchar](100) NOT NULL,
	[SCH_URN] [nvarchar](100) NULL,
	[DateStamp] [datetime] NULL,
 CONSTRAINT [PK_RC_GAE_INTERMEDIATE_] PRIMARY KEY CLUSTERED 
(
	[URN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RC_GAE_INTERMEDIATE] ADD  CONSTRAINT [DF_RC_GAE_INTERMEDIATE_TimeStamp_]  DEFAULT (getdate()) FOR [DateStamp]