CREATE TABLE [dbo].[RC_LODGE_LOOKUP](
	[ORG_ID] [varchar](50) NOT NULL,
	[MASONIC_ORG_CODE] [varchar](100) NOT NULL,
	[ORG_NAME] [varchar](100) NULL,
	[PROVINCE] [varchar](100) NULL,
	[DATE_CREATED] [datetime] NULL,
 CONSTRAINT [PK_RC_LODGE_Number_] PRIMARY KEY CLUSTERED 
(
	[MASONIC_ORG_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]