CREATE TABLE [dbo].[RC_ST_EDRMS_RPP](
	[RPP_DOC_REF] [varchar](500) NOT NULL,
	[FORM_TYPE] [varchar](50) NULL,
	[PER_NUM] [varchar](50) NULL,
	[CHEST_NUMBER] [varchar](50) NULL,
	[CHEST_NAME] [varchar](100) NULL,
	[GENERAL_FUND_FLAG] [char](1) NULL,
	[MASONIC_ORG_CODE] [varchar](50) NULL,
	[ORG_NAME] [varchar](100) NULL,
	[AMOUNT] [varchar](50) NULL,
	[ACCOUNT_NUMBER] [varchar](50) NULL,
	[SORT_CODE] [varchar](50) NULL,
	[START_MONTH] [varchar](50) NULL,
	[START_YEAR] [varchar](50) NULL,
	[TERM] [varchar](50) NULL,
	[FREQUENCY] [varchar](50) NULL,
	[BLANKET_GA_DECL_FLAG] [char](1) NULL,
	[TAX_PAYER_FLAG] [char](1) NULL,
	[NOTES] [varchar](500) NULL,
	[DATE_SIGNED] [datetime] NULL,
	[TITLE] [varchar](100) NULL,
	[FAMILY_NAME] [varchar](100) NULL,
	[GIVEN_NAME] [varchar](200) NULL,
	[INITIALS] [varchar](50) NULL,
	[ADDRESS1] [varchar](100) NULL,
	[ADDRESS2] [varchar](100) NULL,
	[ADDRESS3] [varchar](100) NULL,
	[ADDRESS4] [varchar](100) NULL,
	[ADDRESS5] [varchar](100) NULL,
	[POSTCODE] [varchar](50) NULL,
	[TELEPHONE] [varchar](50) NULL,
	[EMAIL] [varchar](100) NULL,
	[SCANNED_BY] [varchar](100) NULL,
	[SCANNED_DATE] [datetime] NULL,
	[RECOGNISED_BY] [varchar](100) NULL,
	[RECOGNISED_DATE] [datetime] NULL,
	[VERIFIED_BY] [varchar](100) NULL,
	[VERIFICATION_START_DATE] [datetime] NULL,
	[FILE_PATH] [varchar](500) NULL,
	[IN_ORACLE_FLAG] [char](1) NOT NULL,
	[IN_ORACLE_DATE] [datetime] NULL,
	[IN_EXE_FLAG] [char](1) NOT NULL,
	[DATE_CREATED] [datetime] NULL,
	[PAYMENT_START_DATE] [datetime] NULL,
	[FINAL_PAYMENT_DATE] [datetime] NULL,
	[DONOR_NAME] [varchar](100) NULL,
	[SINGLE_AMOUNT] [varchar](50) NULL,
	[SINGLE_MASONIC_ORG_CODE] [varchar](50) NULL,
	[SINGLE_ORG_NAME] [varchar](100) NULL,
	[SINGLE_CHEST_NUMBER] [varchar](50) NULL,
	[SINGLE_GENERAL_FUND_FLAG] [char](1) NULL,
	[SINGLE_IN_ORACLE_FLAG] [char](1) NULL,
	[SINGLE_IN_ORACLE_DATE] [datetime] NULL,
	[BLANKET_GA_DECL_FUTURE_FLAG] [char](1) NULL,
	[SINGLE_CHEST_NAME] [varchar](100) NULL,
	[PAYMENT_METHOD] [varchar](50) NULL,
	[DONATION_SOURCE] [varchar](50) NULL,
	[MISC_FLAG] [bit] NULL,
	[TRANSACTION_GA_DECL_FLAG] [varchar](1) NOT NULL,
	[AUTO_CREATE_DONOR_FLAG] [char](1) NULL,
	[AUTO_CREATE_DONOR_REGULAR_FLAG] [char](1) NULL,
	[FROM_UNIT_FLAG] [char](1) NULL,
	[FROM_OTHER_ORDER_UNIT_FLAG] [char](1) NULL,
	[FROM_OTHER_UNIT_FLAG] [char](1) NULL,
	[UNIT_NUMBER] [varchar](500) NULL,
	[UNIT_NAME] [varchar](500) NULL,
 [APPEAL_NAME] NVARCHAR(500) NULL, 
    CONSTRAINT [PK_RC_ST_EDRMS_RPP_] PRIMARY KEY CLUSTERED 
(
	[RPP_DOC_REF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_RPP] ADD  CONSTRAINT [DF_RC_ST_EDRMS_RPP_BLANKET_GA_DECL_FLAG_]  DEFAULT ('N') FOR [BLANKET_GA_DECL_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_RPP] ADD  CONSTRAINT [DF_RC_ST_EDRMS_RPP_TAX_PAYER_FLAG_]  DEFAULT ('Y') FOR [TAX_PAYER_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_RPP] ADD  CONSTRAINT [DF_RC_ST_EDRMS_RPP_IN_ORACLE_FLAG_]  DEFAULT ('N') FOR [IN_ORACLE_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_RPP] ADD  CONSTRAINT [DF_RC_ST_EDRMS_RPP_IN_EXE_FLAG_]  DEFAULT ('N') FOR [IN_EXE_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_RPP] ADD  CONSTRAINT [DF_RC_ST_EDRMS_RPP_SINGLE_IN_ORACLE_FLAG_]  DEFAULT ('N') FOR [SINGLE_IN_ORACLE_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_RPP] ADD  CONSTRAINT [DF_RC_ST_EDRMS_RPP_BLANKET_GA_DECL_FUTURE_FLAG_]  DEFAULT ('N') FOR [BLANKET_GA_DECL_FUTURE_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_RPP] ADD  CONSTRAINT [DF_RC_ST_EDRMS_RPP_TRANSACTION_GA_DECL_FLAG_]  DEFAULT ('N') FOR [TRANSACTION_GA_DECL_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_RPP] ADD  DEFAULT ('N') FOR [AUTO_CREATE_DONOR_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_RPP] ADD  DEFAULT ('N') FOR [AUTO_CREATE_DONOR_REGULAR_FLAG]