CREATE TABLE [dbo].[RC_ST_EDRMS_SPECIAL](
	[SPECIAL_DOC_REF] [varchar](500) NOT NULL,
	[VOUCHER_NUMBER] [varchar](100) NOT NULL,
	[AMOUNT] [varchar](50) NOT NULL,
	[MASONIC_CHARITY_NAME] [varchar](100) NOT NULL,
	[MASONIC_CHARITY_FORM_POSITION] [varchar](50) NULL,
	[REQUESTED_DATE] [datetime] NULL,
	[CHEST_NUMBER] [varchar](50) NULL,
	[CHEST_NAME] [varchar](100) NULL,
	[SCANNED_BY] [varchar](100) NULL,
	[SCANNED_DATE] [datetime] NULL,
	[RECOGNISED_BY] [varchar](100) NULL,
	[RECOGNISED_DATE] [datetime] NULL,
	[VERIFIED_BY] [varchar](100) NULL,
	[VERIFICATION_START_DATE] [datetime] NULL,
	[FILE_PATH] [varchar](500) NULL,
	[IN_ORACLE_FLAG] [char](1) NOT NULL,
	[IN_ORACLE_DATE] [datetime] NULL,
	[IN_EXE_FLAG] [char](1) NOT NULL,
	[DATE_CREATED] [datetime] NULL,
	[PRINT_CHEQUE_NOW_FLAG] [char](1) NOT NULL,
	[VOUCHER_TYPE] [varchar](50) NULL,
	[REGISTERED_CHARITY_NUMBER] [varchar](100) NULL,
	[RETURN_TO_REP] [char](1) NULL,
	[REP_GIVEN_NAMES] [varchar](100) NULL,
	[REP_FAMILY_NAME] [varchar](100) NULL,
	[REP_ADDRESS_1] [varchar](100) NULL,
	[REP_ADDRESS_2] [varchar](100) NULL,
	[REP_ADDRESS_3] [varchar](100) NULL,
	[REP_ADDRESS_4] [varchar](100) NULL,
	[REP_ADDRESS_5] [varchar](100) NULL,
	[POSTCODE] [varchar](50) NULL,
	[DO_NOT_GROUP_FLAG] [char](1) NULL,
	[COMMENTS] [varchar](1000) NULL,
 CONSTRAINT [PK_RC_ST_EDRMS_SPECIAL_] PRIMARY KEY CLUSTERED 
(
	[SPECIAL_DOC_REF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_SPECIAL] ADD  CONSTRAINT [DF_RC_ST_EDRMS_SPECIAL_IN_ORACLE_FLAG_]  DEFAULT ('N') FOR [IN_ORACLE_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_SPECIAL] ADD  CONSTRAINT [DF_RC_ST_EDRMS_SPECIAL_IN_EXE_FLAG_]  DEFAULT ('N') FOR [IN_EXE_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_SPECIAL] ADD  CONSTRAINT [DF_RC_ST_EDRMS_SPECIAL_print_cheque_now_flag_]  DEFAULT ('N') FOR [PRINT_CHEQUE_NOW_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_SPECIAL] ADD  CONSTRAINT [DF_RC_ST_EDRMS_SPECIAL_VOUCHER_NAME_]  DEFAULT ('Special Vouchers (Blue)') FOR [VOUCHER_TYPE]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_SPECIAL] ADD  CONSTRAINT [DF_RC_ST_EDRMS_SPECIAL_DO_NOT_GROUP_FLAG_]  DEFAULT ('N') FOR [DO_NOT_GROUP_FLAG]