CREATE TABLE [dbo].[RC_ST_EDRMS_NORMAL](
	[NORMAL_DOC_REF] [varchar](500) NOT NULL,
	[VOUCHER_NUMBER] [varchar](100) NOT NULL,
	[AMOUNT] [varchar](50) NOT NULL,
	[CHARITY_ID] [varchar](50) NULL,
	[CHARITY_NAME] [varchar](100) NOT NULL,
	[REGISTERED_CHARITY_NUMBER] [varchar](100) NULL,
	[REQUESTED_DATE] [datetime] NULL,
	[CHEST_NUMBER] [varchar](50) NULL,
	[CHEST_NAME] [varchar](100) NULL,
	[ADDRESS1] [varchar](100) NULL,
	[ADDRESS2] [varchar](100) NULL,
	[ADDRESS3] [varchar](100) NULL,
	[ADDRESS4] [varchar](100) NULL,
	[ADDRESS5] [varchar](100) NULL,
	[POSTCODE] [varchar](50) NULL,
	[PRINT_CHEQUE_NOW_FLAG] [char](1) NOT NULL,
	[CHEST_INTERNAL_TRANSFER_FLAG] [char](1) NOT NULL,
	[DO_NOT_GROUP_FLAG] [char](1) NOT NULL,
	[CREATE_ONE_OFF_ADDRESS_FLAG] [char](1) NOT NULL,
	[SCANNED_BY] [varchar](100) NULL,
	[SCANNED_DATE] [datetime] NULL,
	[RECOGNISED_BY] [varchar](100) NULL,
	[RECOGNISED_DATE] [datetime] NULL,
	[VERIFIED_BY] [varchar](100) NULL,
	[VERIFICATION_START_DATE] [datetime] NULL,
	[FILE_PATH] [varchar](500) NULL,
	[IN_ORACLE_FLAG] [char](1) NOT NULL,
	[IN_ORACLE_DATE] [datetime] NULL,
	[IN_EXE_FLAG] [char](1) NOT NULL,
	[DATE_CREATED] [datetime] NULL,
	[VOUCHER_TYPE] [varchar](50) NULL,
	[RETURN_TO_REP] [char](1) NULL,
	[REP_GIVEN_NAMES] [varchar](100) NULL,
	[REP_FAMILY_NAME] [varchar](100) NULL,
	[REP_ADDRESS_1] [varchar](100) NULL,
	[REP_ADDRESS_2] [varchar](100) NULL,
	[REP_ADDRESS_3] [varchar](100) NULL,
	[REP_ADDRESS_4] [varchar](100) NULL,
	[REP_ADDRESS_5] [varchar](100) NULL,
	[REP_POSTCODE] [varchar](50) NULL,
	[EMERGENCY_FLAG] [char](1) NULL,
	[INTERNAL_TRANSFER_FLAG] [char](1) NULL,
	[EMERGENCY_TRANSFER_FLAG] [char](1) NULL,
	[NORMAL_FLAG] [char](1) NULL,
	[CHARITY_ADDRESS_ID] [char](10) NULL,
	[COMMENTS] [varchar](1000) NULL,
 CONSTRAINT [PK_RC_ST_EDRMS_NORMAL_] PRIMARY KEY CLUSTERED 
(
	[NORMAL_DOC_REF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_NORMAL] ADD  CONSTRAINT [DF_RC_ST_EDRMS_NORMAL_PRINT_CHEQUE_NOW_FLAG_]  DEFAULT ('N') FOR [PRINT_CHEQUE_NOW_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_NORMAL] ADD  CONSTRAINT [DF_RC_ST_EDRMS_NORMAL_CHEST_INTERNAL_TRANSFER_FLAG_]  DEFAULT ('N') FOR [CHEST_INTERNAL_TRANSFER_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_NORMAL] ADD  CONSTRAINT [DF_RC_ST_EDRMS_NORMAL_DO_NOT_GROUP_FLAG_]  DEFAULT ('N') FOR [DO_NOT_GROUP_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_NORMAL] ADD  CONSTRAINT [DF_RC_ST_EDRMS_NORMAL_CREATE_ONE_OFF_ADDRESS_FLAG_]  DEFAULT ('N') FOR [CREATE_ONE_OFF_ADDRESS_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_NORMAL] ADD  CONSTRAINT [DF_RC_ST_EDRMS_NORMAL_IN_ORACLE_FLAG_]  DEFAULT ('N') FOR [IN_ORACLE_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_NORMAL] ADD  CONSTRAINT [DF_RC_ST_EDRMS_NORMAL_IN_EXE_FLAG_]  DEFAULT ('N') FOR [IN_EXE_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_NORMAL] ADD  CONSTRAINT [DF_RC_ST_EDRMS_NORMAL_VOUCHER_TYPE_]  DEFAULT ('Normal Vouchers (Green)') FOR [VOUCHER_TYPE]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_NORMAL] ADD  CONSTRAINT [DF_RC_ST_EDRMS_NORMAL_RETURN_TO_REP_]  DEFAULT ('N') FOR [RETURN_TO_REP]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_NORMAL] ADD  CONSTRAINT [DF_RC_ST_EDRMS_NORMAL_EMERGENCY_FLAG_]  DEFAULT ('N') FOR [EMERGENCY_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_NORMAL] ADD  CONSTRAINT [DF_RC_ST_EDRMS_NORMAL_INTERNAL_TRANSFER_FLAG_]  DEFAULT ('N') FOR [INTERNAL_TRANSFER_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_NORMAL] ADD  CONSTRAINT [DF_RC_ST_EDRMS_NORMAL_EMERGENCY_TRANSFER_FLAG_]  DEFAULT ('N') FOR [EMERGENCY_TRANSFER_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_NORMAL] ADD  CONSTRAINT [DF_RC_ST_EDRMS_NORMAL_NORMAL_FLAG_]  DEFAULT ('N') FOR [NORMAL_FLAG]