CREATE TABLE [dbo].[RC_ST_EDRMS_GA_ENVELOPE](
	[ENVELOPE_DOC_REF] [varchar](500) NOT NULL,
	[SCHEDULE_SCHEDULE_DOC_REF] [varchar](500) NOT NULL,
	[PER_NUM] [varchar](50) NULL,
	[CHEST_NUMBER] [varchar](50) NULL,
	[CHEST_NAME] [varchar](100) NULL,
	[AMOUNT] [varchar](50) NOT NULL,
	[DATE_SIGNED] [datetime] NULL,
	[BLANKET_GA_DECL_FLAG] [char](1) NOT NULL,
	[MISC_FLAG] [char](1) NOT NULL,
	[TITLE] [varchar](50) NULL,
	[GIVEN_NAME] [varchar](200) NULL,
	[FAMILY_NAME] [varchar](100) NULL,
	[INITIALS] [varchar](10) NULL,
	[ADDRESS1] [varchar](100) NULL,
	[ADDRESS2] [varchar](100) NULL,
	[ADDRESS3] [varchar](100) NULL,
	[ADDRESS4] [varchar](100) NULL,
	[ADDRESS5] [varchar](100) NULL,
	[POSTCODE] [varchar](50) NULL,
	[NOTES] [varchar](1000) NULL,
	[SCANNED_BY] [varchar](100) NULL,
	[SCANNED_DATE] [datetime] NULL,
	[RECOGNISED_BY] [varchar](100) NULL,
	[RECOGNISED_DATE] [datetime] NULL,
	[VERIFIED_BY] [varchar](100) NULL,
	[VERIFICATION_START_DATE] [datetime] NULL,
	[FILE_PATH] [varchar](500) NULL,
	[IN_ORACLE_FLAG] [char](1) NOT NULL,
	[IN_ORACLE_DATE] [datetime] NULL,
	[IN_EXE_FLAG] [char](1) NULL,
	[DATE_CREATED] [datetime] NULL,
	[GIFT_AID_TYPE] [varchar](100) NULL,
	[MASONIC_ORG_NAME] [varchar](100) NULL,
	[ORG_CODE] [varchar](50) NULL,
	[DONOR_NAME] [varchar](100) NULL,
	[TRANSACTION_GA_DECL_FLAG] [varchar](1) NOT NULL,
 [FROM_UNIT_FLAG] CHAR NULL, 
    [FROM_OTHER_ORDER_UNIT_FLAG] CHAR NULL, 
    [FROM_OTHER_UNIT_FLAG] CHAR NULL, 
    [UNIT_NAME] VARCHAR(500) NULL, 
    [UNIT_NUMBER] VARCHAR(500) NULL, 
    [PROCESSED_OFF_SITE_FLAG] CHAR NOT NULL DEFAULT 'N', 
    [VALIDATION_REQUIRED_FLAG] CHAR NOT NULL DEFAULT 'N', 
    [BTC_REFERENCE] VARCHAR(1000) NULL, 
    [FULL_ADDRESS] VARCHAR(1000) NULL, 
    [AUTO_CREATE_DONOR_FLAG] CHAR NULL , 
    CONSTRAINT [PK_RC_ST_EDRMS_GA_ENVELOPE_] PRIMARY KEY CLUSTERED 
(
	[ENVELOPE_DOC_REF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_GA_ENVELOPE] ADD  CONSTRAINT [DF_RC_ST_EDRMS_GA_ENVELOPE_MISC_FLAG_]  DEFAULT ('N') FOR [MISC_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_GA_ENVELOPE] ADD  CONSTRAINT [DF_RC_ST_EDRMS_GA_ENVELOPE_IN_ORACLE_FLAG_]  DEFAULT ('N') FOR [IN_ORACLE_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_GA_ENVELOPE] ADD  CONSTRAINT [DF_RC_ST_EDRMS_GA_ENVELOPE_IN_EXE_FLAG_]  DEFAULT ('N') FOR [IN_EXE_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_GA_ENVELOPE] ADD  CONSTRAINT [DF_RC_ST_EDRMS_GA_ENVELOPE_GIFT_AID_TYPE_]  DEFAULT ('Gift Aid Envelopes') FOR [GIFT_AID_TYPE]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_GA_ENVELOPE] ADD  CONSTRAINT [DF_RC_ST_EDRMS_GA_ENVELOPE_TRANSACTION_GA_DECL_FLAG_]  DEFAULT ('N') FOR [TRANSACTION_GA_DECL_FLAG]