CREATE TABLE [dbo].[RC_ST_EDRMS_MISC](
	[MISC_DOC_REF] [varchar](500) NOT NULL,
	[CHEST_NUMBER] [varchar](100) NULL,
	[CHEST_NAME] [varchar](100) NULL,
	[AMOUNT] [varchar](50) NOT NULL,
	[MISC_PAY_DESC] [varchar](1000) NULL,
	[DATE_SIGNED] [datetime] NULL,
	[SCANNED_BY] [varchar](100) NULL,
	[SCANNED_DATE] [datetime] NULL,
	[RECOGNISED_BY] [varchar](100) NULL,
	[RECOGNISED_DATE] [datetime] NULL,
	[VERIFIED_BY] [varchar](100) NULL,
	[VERIFICATION_START_DATE] [datetime] NULL,
	[FILE_PATH] [varchar](500) NULL,
	[IN_ORACLE_FLAG] [char](1) NOT NULL,
	[IN_ORACLE_DATE] [datetime] NULL,
	[IN_EXE_FLAG] [char](1) NOT NULL,
	[DATE_CREATED] [datetime] NULL,
	[PAYMENT_TYPE] [varchar](50) NULL,
	[RECEIPT_REQUIRED] [char](1) NOT NULL,
	[COMMENTS] [varchar](1000) NULL,
	[PAYMENT_METHOD] [varchar](50) NULL,
	[DONATION_SOURCE] [varchar](50) NULL,
	[LUMP_SUM_FLAG] [char](1) NOT NULL,
	[FROM_UNIT_FLAG] [char](1) NULL,
	[FROM_OTHER_ORDER_UNIT_FLAG] [char](1) NULL,
	[FROM_OTHER_UNIT_FLAG] [char](1) NULL,
	[UNIT_NAME] [varchar](500) NULL,
	[UNIT_NUMBER] [varchar](500) NULL,
 CONSTRAINT [PK_RC_ST_EDRMS_MISC_] PRIMARY KEY CLUSTERED 
(
	[MISC_DOC_REF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_MISC] ADD  CONSTRAINT [DF_RC_ST_EDRMS_MISC_IN_ORACLE_FLAG_]  DEFAULT ('N') FOR [IN_ORACLE_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_MISC] ADD  CONSTRAINT [DF_RC_ST_EDRMS_MISC_IN_EXE_FLAG_]  DEFAULT ('N') FOR [IN_EXE_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_MISC] ADD  CONSTRAINT [DF_RC_ST_EDRMS_MISC_PAYMENT_TYPE_]  DEFAULT ('Miscellaneous Payment Form') FOR [PAYMENT_TYPE]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_MISC] ADD  CONSTRAINT [DF_RC_ST_EDRMS_MISC_RECEIPT_REQUIRED_]  DEFAULT ('N') FOR [RECEIPT_REQUIRED]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_MISC] ADD  CONSTRAINT [DF_RC_ST_EDRMS_MISC_LUMP_SUM_FLAG_]  DEFAULT ('N') FOR [LUMP_SUM_FLAG]