CREATE TABLE [dbo].[RC_ST_EDRMS_GA_SCHEDULE](
	[SCHEDULE_DOC_REF] [varchar](500) NOT NULL,
	[MASONIC_ORG_CODE] [varchar](50) NULL,
	[ORG_NAME] [varchar](100) NULL,
	[CHEST_NUMBER] [varchar](50) NOT NULL,
	[CHEST_NAME] [varchar](100) NOT NULL,
	[ACCOUNT_NAME] [varchar](100) NULL,
	[CHEQUE_NUMBER] [varchar](50) NULL,
	[CHEQUE_DATE] [datetime] NULL,
	[AMOUNT] [varchar](50) NOT NULL,
	[NO_OF_ITEMS] [varchar](50) NOT NULL,
	[TITLE] [varchar](50) NULL,
	[GIVEN_NAME] [varchar](200) NULL,
	[FAMILY_NAME] [varchar](100) NULL,
	[INITIALS] [varchar](10) NULL,
	[ADDRESS1] [varchar](100) NULL,
	[ADDRESS2] [varchar](100) NULL,
	[ADDRESS3] [varchar](100) NULL,
	[ADDRESS4] [varchar](100) NULL,
	[ADDRESS5] [varchar](100) NULL,
	[POSTCODE] [varchar](100) NULL,
	[DATE_SIGNED] [datetime] NULL,
	[SCANNED_BY] [varchar](100) NULL,
	[SCANNED_DATE] [datetime] NULL,
	[RECOGNISED_BY] [varchar](100) NULL,
	[RECOGNISED_DATE] [datetime] NULL,
	[VERIFIED_BY] [varchar](100) NULL,
	[VERIFICATION_START_DATE] [datetime] NULL,
	[FILE_PATH] [varchar](500) NULL,
	[IN_ORACLE_FLAG] [char](1) NOT NULL,
	[IN_ORACLE_DATE] [datetime] NULL,
	[IN_EXE_FLAG] [char](1) NOT NULL,
	[DATE_CREATED] [datetime] NULL,
	[GIFT_AID_TYPE] [varchar](100) NULL,
	[DONOR_NAME] [varchar](100) NULL,
 [FROM_UNIT_FLAG] [char](1) NULL,
	[FROM_OTHER_ORDER_UNIT_FLAG] [char](1) NULL,
	[FROM_OTHER_UNIT_FLAG] [char](1) NULL,
	[UNIT_NAME] [varchar](500) NULL,
	[UNIT_NUMBER] [varchar](500) NULL,
	[PROCESSED_OFF_SITE_FLAG] [char](1) NOT NULL default('N'),
	[VALIDATION_REQUIRED_FLAG] [char](1) NOT NULL default ('N'),
	[BTC_REFERENCE] [varchar](1000) NULL,
	[FULL_ADDRESS] [varchar](1000) NULL,
	[TOTAL_GA_DONATIONS] [int] NULL,
	[TOTAL_NON_GA_DONATIONS] [int] NULL,
	[TOTAL_ALL_DONATIONS] [int] NULL,	
    CONSTRAINT [PK_RC_ST_EDRMS_GA_SCHEDULE_] PRIMARY KEY CLUSTERED 
(
	[SCHEDULE_DOC_REF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_GA_SCHEDULE] ADD  CONSTRAINT [DF_RC_ST_EDRMS_GA_SCHEDULE_IN_ORACLE_FLAG_]  DEFAULT ('N') FOR [IN_ORACLE_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_GA_SCHEDULE] ADD  CONSTRAINT [DF_RC_ST_EDRMS_GA_SCHEDULE_IN_EXE_FLAG_]  DEFAULT ('N') FOR [IN_EXE_FLAG]
GO
ALTER TABLE [dbo].[RC_ST_EDRMS_GA_SCHEDULE] ADD  CONSTRAINT [DF_RC_ST_EDRMS_GA_SCHEDULE_GIFT_AID_TYPE_]  DEFAULT ('Gift Aid Envelopes/Sponsorships - Verification Form') FOR [GIFT_AID_TYPE]