CREATE TABLE [dbo].[Transaction](
	[TransactionID] [int] IDENTITY(1,1) NOT NULL,
	[Status] [int] NOT NULL,
	[LastUpdated] [datetime] NULL,
	[MasonicID] [nvarchar](50) NULL,
	[DonorTitle] [nvarchar](255) NULL,
	[DonorFirstName] [nvarchar](255) NULL,
	[DonorSurname] [nvarchar](255) NULL,
	[DonorFullAddress] [nvarchar](255) NULL,
	[DonorPostcode] [nvarchar](255) NULL,
	[DonorEmailAddress] [nvarchar](255) NULL,
	[BankBranchName] [nvarchar](255) NULL,
	[BankBranchAddress] [nvarchar](255) NULL,
	[BankSortCode] [nvarchar](255) NULL,
	[BankAccountNumber] [nvarchar](255) NULL,
	[BankAccountName] [nvarchar](255) NULL,
	[BankIsAccountHolder] [nvarchar](255) NULL,
	[LodgeName] [nvarchar](255) NULL,
	[LodgeNumber] [nvarchar](255) NULL,
	[ChestName] [nvarchar](255) NULL,
	[ChestNumber] [nvarchar](255) NULL,
	[DonationAmount] [decimal](18, 2) NULL,
	[DonationFrequency] [int] NULL,
	[DonationDuration] [int] NULL,
	[DonationStartDate] [datetime] NULL,
	[DonationGiftAidThisDonation] [nvarchar](255) NULL,
	[DonationGiftAidPastFourYears] [nvarchar](255) NULL,
	[DonationGiftAidAllFuture] [nvarchar](255) NULL,
	[AuditIPAddress] [nvarchar](255) NULL,
	[AuditTimestamp] [nvarchar](255) NULL,
	[AuditBrowserInfo] [nvarchar](255) NULL,
	[PaymentMethod] [int] NOT NULL,
	[Source] [int] NOT NULL,
	[XmlSourceData] [nvarchar](max) NULL,
	[OverrideGiftAid] [bit] NOT NULL,
	[Notes] [nvarchar](500) NULL,
	[OverrideLodge] [bit] NOT NULL,
	[DonationType] [int] NOT NULL,
	[Description] [nvarchar](max) NULL,
	[ReceiptRequired] [bit] NOT NULL,
	[LumpSum] [bit] NOT NULL,
	[TransactionTypeId] [int] NOT NULL,
	[CharityName] [nvarchar](255) NULL,
	[CharityContact] [nvarchar](255) NULL,
	[CharityAddress] [nvarchar](4000) NULL,
	[CharityPostcode] [nvarchar](50) NULL,
	[CharityFrequency] [int] NULL,
	[Defer] [bit] NULL,
	[DonorInitials] [nvarchar](50) NULL,
	[DonorDateOfBirth] [datetime] NULL,
	[Phone] [nvarchar](50) NULL,
	[CharityRegNumber] [nvarchar](255) NULL,
	[MasonFlag] [char](1) NOT NULL,
	[IsDonorAnonymous] [char](1) NOT NULL,
	[PassDonorToCharity] [char](1) NOT NULL,
	[AllowCharityContactDonor] [char](1) NOT NULL,
	[DonorAgreedTerms] [char](1) NOT NULL,
	[RelatedTransactionRef] [nvarchar](255) NULL,
	[TransactionRef] [nvarchar](255) NULL,
	[ExportedDocRef] [nvarchar](255) NULL,
	[AutoGenerateDonorFlag] [char](1) NULL,
	[CsvFileId] [nvarchar](255) NULL,
 [OverrideCharity] CHAR NOT NULL DEFAULT ('N'), 
    [OverrideCharitySource] NVARCHAR(255) NULL , 
    [LogIdentifier] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(), 
    [CreatedBy] NVARCHAR(255) NULL, 
    [Beneficiary_Frequency] NVARCHAR(50) NULL, 
    [Beneficiary_Timestamp] DATETIME NULL, 
    CONSTRAINT [PK_Transaction_] PRIMARY KEY CLUSTERED 
(
	[TransactionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Transaction] ADD  CONSTRAINT [DF_Transaction_Status_]  DEFAULT ((0)) FOR [Status]
GO
ALTER TABLE [dbo].[Transaction] ADD  CONSTRAINT [DF_Transaction_LastUpdated_]  DEFAULT (getdate()) FOR [LastUpdated]
GO
ALTER TABLE [dbo].[Transaction] ADD  CONSTRAINT [DF_Transaction_PaymentMethod_]  DEFAULT ((8)) FOR [PaymentMethod]
GO
ALTER TABLE [dbo].[Transaction] ADD  CONSTRAINT [DF_Transaction_Source_]  DEFAULT ((0)) FOR [Source]
GO
ALTER TABLE [dbo].[Transaction] ADD  CONSTRAINT [DF_Transaction_OverrideGiftAid_]  DEFAULT ((0)) FOR [OverrideGiftAid]
GO
ALTER TABLE [dbo].[Transaction] ADD  CONSTRAINT [DF_Transaction_OverrideLodge_]  DEFAULT ((0)) FOR [OverrideLodge]
GO
ALTER TABLE [dbo].[Transaction] ADD  DEFAULT ((0)) FOR [DonationType]
GO
ALTER TABLE [dbo].[Transaction] ADD  DEFAULT ((0)) FOR [TransactionTypeId]
GO
ALTER TABLE [dbo].[Transaction] ADD  DEFAULT ('N') FOR [MasonFlag]
GO
ALTER TABLE [dbo].[Transaction] ADD  DEFAULT ('N') FOR [IsDonorAnonymous]
GO
ALTER TABLE [dbo].[Transaction] ADD  DEFAULT ('N') FOR [PassDonorToCharity]
GO
ALTER TABLE [dbo].[Transaction] ADD  DEFAULT ('N') FOR [AllowCharityContactDonor]
GO
ALTER TABLE [dbo].[Transaction] ADD  DEFAULT ('N') FOR [DonorAgreedTerms]
GO
ALTER TABLE [dbo].[Transaction] ADD  DEFAULT ('N') FOR [AutoGenerateDonorFlag]